In [1]:
import numpy as np
from sklearn import preprocessing
input_data = np.random.uniform(-6.0,6.0, size=(4,3))
print(input_data)

[[-0.28648651  2.7342139  -2.11928544]
 [-5.20514234 -0.05830966 -2.90612415]
 [ 4.45353943 -1.75998009 -5.32499803]
 [ 5.48823384 -3.31518587 -2.8958845 ]]


In [2]:
# Lakukanlah binarization terhadap input_data dengan threshold 0.7

data_binarized = preprocessing.Binarizer(threshold=0.7).transform(input_data)
print("Binarized data:\n", data_binarized)

Binarized data:
 [[0. 1. 0.]
 [0. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [3]:
# Lakukanlah scalling dengan kedua metode normalization terhadap input_data

scaler1 = preprocessing.MinMaxScaler()
scaled_data1 = scaler1.fit_transform(input_data)
print ("Min Max scaled data:\n", scaled_data1,'\n')

scaler2 = preprocessing.MaxAbsScaler()
scaled_data2 = scaler2.fit_transform(input_data)
print ("Max Abs scaled data:\n", scaled_data2,'\n')

Min Max scaled data:
 [[0.45997221 1.         1.        ]
 [0.         0.53838006 0.75455108]
 [0.90323969 0.25708431 0.        ]
 [1.         0.         0.75774526]] 

Max Abs scaled data:
 [[-0.05220013  0.82475433 -0.39798802]
 [-0.94841847 -0.01758866 -0.54575122]
 [ 0.81147042 -0.53088429 -1.        ]
 [ 1.         -1.         -0.54382828]] 



In [4]:
# Lakukanlah scaling dengan metode standardization terhadap input_data

std_scaler = preprocessing.StandardScaler()
std_data = std_scaler.fit_transform(input_data)
print ("Normalized data:\n", std_data)

Normalized data:
 [[-0.32934284  1.48626741  0.98906586]
 [-1.48723981  0.24139631  0.33634138]
 [ 0.78650302 -0.51718649 -1.67024295]
 [ 1.03007963 -1.21047723  0.34483571]]


In [5]:
import pandas as pd

df = pd.DataFrame({
    'name': ['J.A.R.V.I.S', 'WALL-E', 'Baymax', 'BB-8', 'Cortana'],
    'color': ['blue', 'brown', 'white', 'yellow', 'blue'],
    'type': ['live', 'cartoon', 'cartoon', 'live', 'cartoon' ]
    })
df

name   color     type
0  J.A.R.V.I.S    blue     live
1       WALL-E   brown  cartoon
2       Baymax   white  cartoon
3         BB-8  yellow     live
4      Cortana    blue  cartoon

In [6]:
# Lakukanlah label encoding terhadap kolom type

df['encoded_color'] = preprocessing.LabelEncoder().fit_transform(df.color)
df

name   color     type  encoded_color
0  J.A.R.V.I.S    blue     live              0
1       WALL-E   brown  cartoon              1
2       Baymax   white  cartoon              2
3         BB-8  yellow     live              3
4      Cortana    blue  cartoon              0

In [10]:
# Lakukanlah one-hot encoding terhadap kolom type

type_columns = []
for t in df['type'].unique():
  type_columns.append(t)

onehot_encoded_type = preprocessing.OneHotEncoder().fit_transform(df[['type']])
df2 = pd.DataFrame(onehot_encoded_type.toarray(), columns=type_columns)
pd.concat([df, df2], axis=1)

name   color     type  encoded_color  live  cartoon
0  J.A.R.V.I.S    blue     live              0   0.0      1.0
1       WALL-E   brown  cartoon              1   1.0      0.0
2       Baymax   white  cartoon              2   1.0      0.0
3         BB-8  yellow     live              3   0.0      1.0
4      Cortana    blue  cartoon              0   1.0      0.0

In [12]:
# Lakukanlah loading dataset iris

from sklearn.datasets import load_iris
iris = load_iris()
X = iris.data
y = iris.target
feature_names = iris.feature_names
target_names = iris.target_names
print("Feature names:", feature_names)
print("Target names:", target_names)
print("First 10 rows of X:\n", X[:10])

Feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target names: ['setosa' 'versicolor' 'virginica']
First 10 rows of X:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


In [13]:
# Lakukanlah splitting dataset

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=1
)

print(X_train.shape)
print(X_test.shape)

print(y_train.shape)
print(y_test.shape)

(120, 4)
(30, 4)
(120,)
(30,)


In [16]:
# Lakukanlah training model menggunakan algoritma KNN ( atau boleh juga mencoba dengan algoritma lain) dengan parameter neighbor bebas
# tampilkan juga akurasi dari model yang dihasilkan
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics

classifier = KNeighborsClassifier(n_neighbors = 3)
classifier.fit(X_train,y_train)
y_pred = classifier.predict(X_test)

# Finding accuracy by comparing actual response values(y_test)with predicted response value(y_pred)
print("Accuracy:", metrics.accuracy_score(y_test, y_pred))

# Providing sample data and the model will make prediction out of that data
sample = [[5, 5, 3, 2], [2, 4, 3, 5]]
preds = classifier.predict(sample)
pred_species = [iris.target_names[p] for p in preds] 
print("Predictions:", pred_species)

Accuracy: 1.0
Predictions: ['versicolor', 'virginica']


In [17]:
# Simpanlah model yang telah di training sebelumnya menggunakan joblib

import joblib
joblib.dump(classifier, 'iris_classifier_KNN.joblib')

['iris_classifier_KNN.joblib']

In [18]:
# Load model yang telah di save sebelumnya

joblib.load('iris_classifier_KNN.joblib')

KNeighborsClassifier(n_neighbors=3)