In [ ]:
#1)
import numpy as np

vektor = np.linspace(5, 50, 10)

print(vektor)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [ ]:
#2)
matriks_identitas = np.eye(3)
print(matriks_identitas)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
#3)
x = np.random.randint(10, 31, size=(1, 5))
rata_rata = np.mean(x)
variansi = np.var(x)
standar_deviasi = np.std(x)

print(rata_rata, variansi, standar_deviasi)

15.0 22.8 4.774934554525329


In [8]:
#4)
arr1 = np.array([3, 4])
arr2 = np.array([1, 0])
rata_rata = (arr1 + arr2) / 2

print(rata_rata)

[2. 2.]


In [10]:
#5)
x = np.linspace(5, 50, 10)
akar = np.sqrt(x)

print(akar)

[2.23606798 3.16227766 3.87298335 4.47213595 5.         5.47722558
 5.91607978 6.32455532 6.70820393 7.07106781]
